name: dd-ger-berlin
title: Versammlungen im Land Berlin
publisher:
  name: Polizei Berlin
  url: https://www.berlin.de/polizei/service/versammlungsbehoerde/versammlungen-aufzuege/
extract:
  sources:
    - uri: https://www.berlin.de/polizei/service/versammlungsbehoerde/versammlungen-aufzuege/index.php/index/all.csv
      pandas:
        read:
          options:
            sep: ";"
            encoding: utf-8
            dtype: str
transform:
  handler: /datasets/dd-ger-berlin/transform.py:handle
load:
  index_uri: s3://demodiff/dd-ger-berlin/index-DATE.json
  entities_uri: s3://demodiff/dd-ger-berlin/entities-DATE.ftm.json
aggregate: false
