name: datasets

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch: {}
  push: {}

jobs:
  data:
    runs-on: ubuntu-latest
    container: ghcr.io/demodiff/demos:main
    strategy:
      matrix:
        dataset:
          - dd-ger-berlin
          # - dd-ger-dresden
    steps:
      - name: parse and write the datasets
        run: "investigraph run -c /datasets/${{ matrix.dataset }}/config.yml"
